; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32-s3-devkitc-1] ;8n
;[env:dfrobot_firebeetle2_esp32s3] ;4n
;[env:esp32dev]

platform = espressif32
board = esp32-s3-devkitc-1
;board = dfrobot_firebeetle2_esp32s3
;board = esp32dev
framework = arduino

board_upload.flash_size = 8MB
board_build.partitions = partitions_ota.csv

build_flags =
    -DCONFIG_ASYNC_TCP_QUEUE_SIZE=128
    -DCONFIG_BOOTLOADER_APP_ROLLBACK_ENABLE=y

lib_deps =
    ESP32Async/AsyncTCP@3.4.10
    ESP32Async/ESPAsyncWebServer@3.6.2
