; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32-s3-devkitc-1] ;8n
; [env:dfrobot_firebeetle2_esp32s3] ;4n
; [env:esp32dev]

platform = espressif32

board = dfrobot_firebeetle2_esp32s3
; board = esp32dev

framework = arduino


; ; Tell PIO to also scan your Arduino libraries folder
; lib_extra_dirs =
;     C:/Users/mehed/Documents/Arduino/libraries

; ; …but ignore the STM32-only Ethernet lib
; lib_ignore =
;     STM32duino_STM32Ethernet

lib_deps =
    painlessmesh/painlessMesh@^1.5.4    
    crankyoldgit/IRremoteESP8266@^2.8.6
    z3t0/IRremote@^4.4.3
    emelianov/modbus-esp8266@^4.1.0