; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32-s3-devkitc-1] ;8n
; [env:dfrobot_firebeetle2_esp32s3] ;4n
; [env:esp32dev]

platform = espressif32

board = esp32-s3-devkitc-1
; board = esp32dev

framework = arduino

board_upload.flash_size = 8MB
board_build.partitions = partitions_ota.csv
board_build.sdkconfig_options =
    CONFIG_BOOTLOADER_APP_ROLLBACK_ENABLE=y

build_flags =
    -DCONFIG_ASYNC_TCP_QUEUE_SIZE=128
    -DCONFIG_BOOTLOADER_APP_ROLLBACK_ENABLE=y

; ; Tell PIO to also scan your Arduino libraries folder
; lib_extra_dirs =
;     C:/Users/mehed/Documents/Arduino/libraries

; ; …but ignore the STM32-only Ethernet lib
; lib_ignore =
;     STM32duino_STM32Ethernet

; Pin one AsyncTCP (v3.4.10) for painlessMesh + portal; tags must include leading "v".
lib_deps =
    ESP32Async/AsyncTCP@3.4.10
    painlessmesh/painlessMesh@^1.5.4
    crankyoldgit/IRremoteESP8266@^2.8.6
    emelianov/modbus-esp8266@^4.1.0
    ESP32Async/ESPAsyncWebServer@3.6.2
    bblanchon/ArduinoJson@^6.21.5
